# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=120, unique=True, verbose_name='Domain')),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='Ip adress')),
                ('port', models.PositiveIntegerField(blank=True, verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'ordering': ('domain', 'ip'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([('domain', 'ip', 'slug')]),
        ),
    ]
