# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='addr',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
