# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microb', '0002_instance_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='addr',
            new_name='url',
        ),
    ]
