# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microb', '0003_auto_20180407_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
