# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microb', '0005_auto_20180407_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='ping_channel',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
